const makeEdge = (u, v, weight) => ({
  id: `${Math.min(u, v)}-${Math.max(u, v)}`,
  u,
  v,
  weight,
})

export const GRAPHS = {
  steiner_advantage: {
    id: 'steiner_advantage',
    name: 'Steiner Advantage',
    description: 'A relay node pulls the three terminals together more cheaply than a direct spanning tree.',
    insight: 'Node 4 acts as a relay and cuts the total cost well below an MST or SPT.',
    nodes: [
      { id: 0, label: 'A', x: 110, y: 240 },
      { id: 1, label: 'B', x: 235, y: 120 },
      { id: 2, label: 'C', x: 235, y: 360 },
      { id: 3, label: 'D', x: 390, y: 80 },
      { id: 4, label: 'R', x: 410, y: 240 },
      { id: 5, label: 'E', x: 390, y: 400 },
      { id: 6, label: 'G', x: 560, y: 190 },
      { id: 7, label: 'H', x: 560, y: 340 },
    ],
    edges: [
      makeEdge(0, 1, 2),
      makeEdge(0, 2, 6),
      makeEdge(1, 3, 3),
      makeEdge(1, 4, 4),
      makeEdge(2, 4, 2),
      makeEdge(2, 5, 4),
      makeEdge(3, 4, 1),
      makeEdge(3, 6, 6),
      makeEdge(4, 5, 3),
      makeEdge(4, 6, 2),
      makeEdge(4, 7, 5),
      makeEdge(5, 7, 3),
      makeEdge(6, 7, 2),
    ],
    defaultTerminals: [0, 3, 6],
  },
  base_case: {
    id: 'base_case',
    name: 'Base Case',
    description: 'A tiny graph with two terminals for tracing the DP by hand.',
    insight: 'The first DP layer is just shortest paths from each terminal, which makes the recurrence concrete.',
    nodes: [
      { id: 0, label: 'A', x: 140, y: 240 },
      { id: 1, label: 'B', x: 270, y: 120 },
      { id: 2, label: 'C', x: 270, y: 360 },
      { id: 3, label: 'D', x: 430, y: 220 },
      { id: 4, label: 'E', x: 560, y: 240 },
    ],
    edges: [
      makeEdge(0, 1, 2),
      makeEdge(0, 2, 5),
      makeEdge(1, 2, 3),
      makeEdge(1, 3, 4),
      makeEdge(2, 3, 2),
      makeEdge(3, 4, 3),
    ],
    defaultTerminals: [0, 3],
  },
  mst_inefficiency: {
    id: 'mst_inefficiency',
    name: 'MST Inefficiency',
    description: 'MST spans every node, including many non-terminals that multicast does not need.',
    insight: 'The MST drags in side branches that do not help connect the selected terminals efficiently.',
    nodes: [
      { id: 0, label: 'A', x: 90, y: 250 },
      { id: 1, label: 'B', x: 190, y: 120 },
      { id: 2, label: 'C', x: 190, y: 380 },
      { id: 3, label: 'D', x: 300, y: 240 },
      { id: 4, label: 'E', x: 410, y: 90 },
      { id: 5, label: 'F', x: 410, y: 390 },
      { id: 6, label: 'G', x: 520, y: 240 },
      { id: 7, label: 'H', x: 620, y: 120 },
      { id: 8, label: 'I', x: 620, y: 370 },
    ],
    edges: [
      makeEdge(0, 1, 3),
      makeEdge(0, 2, 4),
      makeEdge(1, 3, 3),
      makeEdge(2, 3, 3),
      makeEdge(1, 4, 4),
      makeEdge(2, 5, 4),
      makeEdge(3, 4, 2),
      makeEdge(3, 5, 2),
      makeEdge(3, 6, 3),
      makeEdge(4, 7, 3),
      makeEdge(5, 8, 3),
      makeEdge(6, 7, 5),
      makeEdge(6, 8, 5),
      makeEdge(7, 8, 4),
    ],
    defaultTerminals: [0, 6, 8],
  },
  dijkstra_bias: {
    id: 'dijkstra_bias',
    name: 'Dijkstra Bias',
    description: 'Single-source paths can miss a cheaper shared relay that Steiner discovers.',
    insight: 'A relay near the center produces shared routing that shortest paths from one source do not maximize.',
    nodes: [
      { id: 0, label: 'S', x: 120, y: 250 },
      { id: 1, label: 'A', x: 240, y: 120 },
      { id: 2, label: 'B', x: 240, y: 380 },
      { id: 3, label: 'R', x: 390, y: 250 },
      { id: 4, label: 'T1', x: 560, y: 140 },
      { id: 5, label: 'T2', x: 560, y: 360 },
      { id: 6, label: 'X', x: 690, y: 250 },
    ],
    edges: [
      makeEdge(0, 1, 2),
      makeEdge(0, 2, 2),
      makeEdge(1, 3, 3),
      makeEdge(2, 3, 3),
      makeEdge(1, 4, 5),
      makeEdge(2, 5, 5),
      makeEdge(3, 4, 2),
      makeEdge(3, 5, 2),
      makeEdge(4, 6, 2),
      makeEdge(5, 6, 2),
      makeEdge(3, 6, 3),
    ],
    defaultTerminals: [0, 4, 5],
  },
  real_world: {
    id: 'real_world',
    name: 'Real-World Analogy',
    description: 'A city-like network with four terminals and several possible relay hubs.',
    insight: 'Steiner routing chooses only strategic relay intersections to reduce long-haul link cost.',
    nodes: [
      { id: 0, label: 'N1', x: 80, y: 120 },
      { id: 1, label: 'N2', x: 80, y: 300 },
      { id: 2, label: 'N3', x: 180, y: 210 },
      { id: 3, label: 'N4', x: 290, y: 100 },
      { id: 4, label: 'N5', x: 290, y: 320 },
      { id: 5, label: 'N6', x: 400, y: 210 },
      { id: 6, label: 'N7', x: 510, y: 90 },
      { id: 7, label: 'N8', x: 510, y: 330 },
      { id: 8, label: 'N9', x: 620, y: 170 },
      { id: 9, label: 'N10', x: 620, y: 380 },
      { id: 10, label: 'N11', x: 730, y: 100 },
      { id: 11, label: 'N12', x: 730, y: 300 },
    ],
    edges: [
      makeEdge(0, 2, 4),
      makeEdge(1, 2, 3),
      makeEdge(2, 3, 3),
      makeEdge(2, 4, 3),
      makeEdge(3, 5, 4),
      makeEdge(4, 5, 2),
      makeEdge(3, 6, 4),
      makeEdge(4, 7, 4),
      makeEdge(5, 6, 3),
      makeEdge(5, 7, 3),
      makeEdge(6, 8, 2),
      makeEdge(7, 9, 2),
      makeEdge(8, 10, 3),
      makeEdge(8, 11, 4),
      makeEdge(9, 11, 3),
      makeEdge(7, 11, 4),
      makeEdge(5, 8, 4),
      makeEdge(5, 9, 4),
    ],
    defaultTerminals: [0, 6, 9, 11],
  },
}